 import React from 'react'
 import {Card} from './Components/Cards/Card'
 import User from './Components/User/User'
  
 
const getLogo = (domain) =>
  `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;

const jobs = [
  {
    id: 1,
    brandLogo: getLogo("amazon.com"),
    brandName: "Amazon",
    tag1: "Part-Time",
    tag2: "Senior Level",
    datePosted: "5 days ago",
    category: "Senior UI/UX Designer",
    chargePerHour: "$120/hr",
    location: "Mumbai, India",
  },
  {
    id: 2,
    brandLogo: getLogo("google.com"),
    brandName: "Google",
    tag1: "Part-Time",
    tag2: "Flexible Schedule",
    datePosted: "3 days ago",
    category: "Graphic Designer",
    chargePerHour: "$150/hr",
    location: "Kochi, India",
  },
  {
    id: 3,
    brandLogo: getLogo("dribbble.com"),
    brandName: "Dribbble",
    tag1: "Contract",
    tag2: "Remote",
    datePosted: "18 days ago",
    category: "Senior Motion Designer",
    chargePerHour: "$85/hr",
    location: "Chennai, India",
  },
  {
    id: 4,
    brandLogo: getLogo("figma.com"),
    brandName: "Figma",
    tag1: "Full-Time",
    tag2: "In Office",
    datePosted: "5 days ago",
    category: "UX Designer",
    chargePerHour: "$200/hr",
    location: "Bangalore, India",
  },
  {
    id: 5,
    brandLogo: getLogo("airbnb.com"),
    brandName: "Airbnb",
    tag1: "Contract",
    tag2: "Remote",
    datePosted: "5 days ago",
    category: "Junior UI/UX Designer",
    chargePerHour: "$100/hr",
    location: "Delhi, India",
  },
  {
    id: 6,
    brandLogo: getLogo("apple.com"),
    brandName: "Apple",
    tag1: "Full-Time",
    tag2: "Flexible Schedule",
    datePosted: "5 days ago",
    category: "Graphic Designer",
    chargePerHour: "$85/hr",
    location: "Kerala, India",
  },
  {
    id: 7,
    brandLogo: getLogo("spotify.com"),
    brandName: "Spotify",
    tag1: "Part-Time",
    tag2: "Remote",
    datePosted: "2 days ago",
    category: "Product Designer",
    chargePerHour: "$95/hr",
    location: "Hyderabad, India",
  },
  {
    id: 8,
    brandLogo: getLogo("microsoft.com"),
    brandName: "Microsoft",
    tag1: "Full-Time",
    tag2: "Senior Level",
    datePosted: "1 day ago",
    category: "Visual Designer",
    chargePerHour: "$140/hr",
    location: "Pune, India",
  },
  {
    id: 9,
    brandLogo: getLogo("adobe.com"),
    brandName: "Adobe",
    tag1: "Contract",
    tag2: "Remote",
    datePosted: "7 days ago",
    category: "Creative Designer",
    chargePerHour: "$110/hr",
    location: "Noida, India",
  },
  {
    id: 10,
    brandLogo: getLogo("netflix.com"),
    brandName: "Netflix",
    tag1: "Full-Time",
    tag2: "Flexible Schedule",
    datePosted: "4 days ago",
    category: "Motion Graphics Designer",
    chargePerHour: "$130/hr",
    location: "Gurugram, India",
  },
  {
    id: 11,
    brandLogo: getLogo("nike.com"),
    brandName: "Nike",
    tag1: "Full-Time",
    tag2: "In Office",
    datePosted: "2 days ago",
    category: "Brand Designer",
    chargePerHour: "$125/hr",
    location: "New York, USA",
  },
  {
    id: 12,
    brandLogo: getLogo("uber.com"),
    brandName: "Uber",
    tag1: "Contract",
    tag2: "Remote",
    datePosted: "6 days ago",
    category: "Product Designer",
    chargePerHour: "$115/hr",
    location: "San Francisco, USA",
  },
  {
    id: 13,
    brandLogo: getLogo("slack.com"),
    brandName: "Slack",
    tag1: "Full-Time",
    tag2: "Remote",
    datePosted: "3 days ago",
    category: "UI Designer",
    chargePerHour: "$105/hr",
    location: "Austin, USA",
  },
  {
    id: 14,
    brandLogo: getLogo("notion.so"),
    brandName: "Notion",
    tag1: "Part-Time",
    tag2: "Flexible Schedule",
    datePosted: "1 day ago",
    category: "Product Designer",
    chargePerHour: "$135/hr",
    location: "Seattle, USA",
  },
  {
    id: 15,
    brandLogo: getLogo("zoom.us"),
    brandName: "Zoom",
    tag1: "Full-Time",
    tag2: "Remote",
    datePosted: "8 days ago",
    category: "UX Researcher",
    chargePerHour: "$100/hr",
    location: "Boston, USA",
  },
  {
    id: 16,
    brandLogo: getLogo("paypal.com"),
    brandName: "PayPal",
    tag1: "Contract",
    tag2: "Senior Level",
    datePosted: "4 days ago",
    category: "Visual Designer",
    chargePerHour: "$145/hr",
    location: "London, UK",
  },
  {
    id: 17,
    brandLogo: getLogo("shopify.com"),
    brandName: "Shopify",
    tag1: "Full-Time",
    tag2: "Remote",
    datePosted: "2 days ago",
    category: "E-commerce Designer",
    chargePerHour: "$110/hr",
    location: "Toronto, Canada",
  },
  {
    id: 18,
    brandLogo: getLogo("intel.com"),
    brandName: "Intel",
    tag1: "Full-Time",
    tag2: "In Office",
    datePosted: "9 days ago",
    category: "UI/UX Designer",
    chargePerHour: "$130/hr",
    location: "San Jose, USA",
  },
  {
    id: 19,
    brandLogo: getLogo("samsung.com"),
    brandName: "Samsung",
    tag1: "Contract",
    tag2: "Flexible Schedule",
    datePosted: "5 days ago",
    category: "Product Designer",
    chargePerHour: "$120/hr",
    location: "Seoul, South Korea",
  },
  {
    id: 20,
    brandLogo: getLogo("nvidia.com"),
    brandName: "NVIDIA",
    tag1: "Full-Time",
    tag2: "Senior Level",
    datePosted: "3 days ago",
    category: "Motion Designer",
    chargePerHour: "$160/hr",
    location: "California, USA",
  },
  {
    id: 21,
    brandLogo: getLogo("ibm.com"),
    brandName: "IBM",
    tag1: "Full-Time",
    tag2: "Remote",
    datePosted: "7 days ago",
    category: "Visual Designer",
    chargePerHour: "$140/hr",
    location: "New York, USA",
  },
  {
    id: 22,
    brandLogo: getLogo("cisco.com"),
    brandName: "Cisco",
    tag1: "Part-Time",
    tag2: "Remote",
    datePosted: "4 days ago",
    category: "UI Designer",
    chargePerHour: "$95/hr",
    location: "Bangalore, India",
  },
  {
    id: 23,
    brandLogo: getLogo("dell.com"),
    brandName: "Dell",
    tag1: "Full-Time",
    tag2: "In Office",
    datePosted: "6 days ago",
    category: "Graphic Designer",
    chargePerHour: "$105/hr",
    location: "Hyderabad, India",
  },
  {
    id: 24,
    brandLogo: getLogo("hp.com"),
    brandName: "HP",
    tag1: "Contract",
    tag2: "Remote",
    datePosted: "2 days ago",
    category: "Brand Designer",
    chargePerHour: "$90/hr",
    location: "Pune, India",
  },
  {
    id: 25,
    brandLogo: getLogo("sony.com"),
    brandName: "Sony",
    tag1: "Full-Time",
    tag2: "Senior Level",
    datePosted: "5 days ago",
    category: "Motion Graphics Designer",
    chargePerHour: "$150/hr",
    location: "Tokyo, Japan",
  },
  {
    id: 26,
    brandLogo: getLogo("pinterest.com"),
    brandName: "Pinterest",
    tag1: "Part-Time",
    tag2: "Remote",
    datePosted: "1 day ago",
    category: "Creative Designer",
    chargePerHour: "$115/hr",
    location: "San Francisco, USA",
  },
  {
    id: 27,
    brandLogo: getLogo("meta.com"),
    brandName: "Meta",
    tag1: "Full-Time",
    tag2: "Flexible Schedule",
    datePosted: "3 days ago",
    category: "Product Designer",
    chargePerHour: "$175/hr",
    location: "Menlo Park, USA",
  },
  {
    id: 28,
    brandLogo: getLogo("instagram.com"),
    brandName: "Instagram",
    tag1: "Contract",
    tag2: "Remote",
    datePosted: "8 days ago",
    category: "Social Media Designer",
    chargePerHour: "$100/hr",
    location: "Los Angeles, USA",
  },
  {
    id: 29,
    brandLogo: getLogo("linkedin.com"),
    brandName: "LinkedIn",
    tag1: "Full-Time",
    tag2: "Senior Level",
    datePosted: "2 days ago",
    category: "UX Designer",
    chargePerHour: "$145/hr",
    location: "Bangalore, India",
  },
  {
    id: 30,
    brandLogo: getLogo("reddit.com"),
    brandName: "Reddit",
    tag1: "Part-Time",
    tag2: "Remote",
    datePosted: "4 days ago",
    category: "Visual Designer",
    chargePerHour: "$110/hr",
    location: "Chicago, USA",
  },
  {
    id: 31,
    brandLogo: getLogo("twitch.tv"),
    brandName: "Twitch",
    tag1: "Contract",
    tag2: "Flexible Schedule",
    datePosted: "5 days ago",
    category: "Motion Designer",
    chargePerHour: "$125/hr",
    location: "Seattle, USA",
  },
  {
    id: 32,
    brandLogo: getLogo("discord.com"),
    brandName: "Discord",
    tag1: "Full-Time",
    tag2: "Remote",
    datePosted: "2 days ago",
    category: "Brand Designer",
    chargePerHour: "$130/hr",
    location: "San Francisco, USA",
  },
  {
    id: 33,
    brandLogo: getLogo("dropbox.com"),
    brandName: "Dropbox",
    tag1: "Full-Time",
    tag2: "Flexible Schedule",
    datePosted: "7 days ago",
    category: "Product Designer",
    chargePerHour: "$135/hr",
    location: "Austin, USA",
  },
  {
    id: 34,
    brandLogo: getLogo("github.com"),
    brandName: "GitHub",
    tag1: "Full-Time",
    tag2: "Remote",
    datePosted: "3 days ago",
    category: "UI/UX Designer",
    chargePerHour: "$150/hr",
    location: "Boston, USA",
  },
  {
    id: 35,
    brandLogo: getLogo("gitlab.com"),
    brandName: "GitLab",
    tag1: "Contract",
    tag2: "Remote",
    datePosted: "6 days ago",
    category: "Web Designer",
    chargePerHour: "$105/hr",
    location: "Remote, USA",
  },
  {
    id: 36,
    brandLogo: getLogo("atlassian.com"),
    brandName: "Atlassian",
    tag1: "Full-Time",
    tag2: "Senior Level",
    datePosted: "1 day ago",
    category: "Product Designer",
    chargePerHour: "$155/hr",
    location: "Sydney, Australia",
  },
  {
    id: 37,
    brandLogo: getLogo("canva.com"),
    brandName: "Canva",
    tag1: "Part-Time",
    tag2: "Remote",
    datePosted: "4 days ago",
    category: "Graphic Designer",
    chargePerHour: "$95/hr",
    location: "Sydney, Australia",
  },
  {
    id: 38,
    brandLogo: getLogo("wix.com"),
    brandName: "Wix",
    tag1: "Full-Time",
    tag2: "In Office",
    datePosted: "5 days ago",
    category: "Web Designer",
    chargePerHour: "$100/hr",
    location: "Tel Aviv, Israel",
  },
  {
    id: 39,
    brandLogo: getLogo("wordpress.org"),
    brandName: "WordPress",
    tag1: "Contract",
    tag2: "Remote",
    datePosted: "3 days ago",
    category: "WordPress Designer",
    chargePerHour: "$85/hr",
    location: "Delhi, India",
  },
  {
    id: 40,
    brandLogo: getLogo("salesforce.com"),
    brandName: "Salesforce",
    tag1: "Full-Time",
    tag2: "Flexible Schedule",
    datePosted: "2 days ago",
    category: "UX Designer",
    chargePerHour: "$140/hr",
    location: "Hyderabad, India",
  },
  {
    id: 41,
    brandLogo: getLogo("stripe.com"),
    brandName: "Stripe",
    tag1: "Full-Time",
    tag2: "Remote",
    datePosted: "6 days ago",
    category: "Product Designer",
    chargePerHour: "$165/hr",
    location: "Dublin, Ireland",
  },
  {
    id: 42,
    brandLogo: getLogo("tesla.com"),
    brandName: "Tesla",
    tag1: "Full-Time",
    tag2: "In Office",
    datePosted: "4 days ago",
    category: "Industrial Designer",
    chargePerHour: "$150/hr",
    location: "Austin, USA",
  },
  {
    id: 43,
    brandLogo: getLogo("toyota.com"),
    brandName: "Toyota",
    tag1: "Contract",
    tag2: "Senior Level",
    datePosted: "8 days ago",
    category: "Automotive Designer",
    chargePerHour: "$125/hr",
    location: "Tokyo, Japan",
  },
  {
    id: 44,
    brandLogo: getLogo("mercedes-benz.com"),
    brandName: "Mercedes-Benz",
    tag1: "Full-Time",
    tag2: "In Office",
    datePosted: "5 days ago",
    category: "Visual Designer",
    chargePerHour: "$170/hr",
    location: "Stuttgart, Germany",
  },
  {
    id: 45,
    brandLogo: getLogo("bmw.com"),
    brandName: "BMW",
    tag1: "Full-Time",
    tag2: "Senior Level",
    datePosted: "3 days ago",
    category: "Automotive UI Designer",
    chargePerHour: "$160/hr",
    location: "Munich, Germany",
  },
  {
    id: 46,
    brandLogo: getLogo("adidas.com"),
    brandName: "Adidas",
    tag1: "Part-Time",
    tag2: "Remote",
    datePosted: "1 day ago",
    category: "Brand Designer",
    chargePerHour: "$110/hr",
    location: "Berlin, Germany",
  },
  {
    id: 47,
    brandLogo: getLogo("puma.com"),
    brandName: "Puma",
    tag1: "Contract",
    tag2: "Flexible Schedule",
    datePosted: "7 days ago",
    category: "Graphic Designer",
    chargePerHour: "$95/hr",
    location: "London, UK",
  },
  {
    id: 48,
    brandLogo: getLogo("coca-cola.com"),
    brandName: "Coca-Cola",
    tag1: "Full-Time",
    tag2: "In Office",
    datePosted: "2 days ago",
    category: "Creative Designer",
    chargePerHour: "$130/hr",
    location: "Atlanta, USA",
  },
  {
    id: 49,
    brandLogo: getLogo("mcdonalds.com"),
    brandName: "McDonald's",
    tag1: "Contract",
    tag2: "Remote",
    datePosted: "5 days ago",
    category: "Marketing Designer",
    chargePerHour: "$90/hr",
    location: "Chicago, USA",
  },
  {
    id: 50,
    brandLogo: getLogo("figma.com"),
    brandName: "Figma",
    tag1: "Full-Time",
    tag2: "Remote",
    datePosted: "1 day ago",
    category: "Senior Product Designer",
    chargePerHour: "$180/hr",
    location: "San Francisco, USA",
  },
];



  
 
 export const App = () => {
   return (
      <div className='parent'>
          
     {jobs.map(function(chau) {
             return  <Card brandLogo = {chau.brandLogo} brandName = {chau.brandName} tag1 = {chau.tag1} tag2 = {chau.tag2} datePosted = {chau.datePosted} category = {chau.category} chargePerHour = {chau.chargePerHour} location = {chau.location} />
          })}
         
        
    </div>
   )
 }
 


      
   


 export default App;
 